# carla original variable name is used unchanged here (i.e CamelCase, etc)
carla:
  host: localhost
  port: 2000
  QualityLevel: Low  # Low or Epic
  SynchronousMode: False

  sensors:
    CameraRGB:
      SensorType: CAMERA
      carla_settings:
        PostProcessing: SceneFinal
        ImageSizeX: 640
        ImageSizeY: 480
        FOV: 90
        PositionX: 1.80
        PositionY: 0
        PositionZ: 1.30
        RotationPitch: 0
        RotationRoll: 0
        RotationYaw: 0

    camera_depth:
      SensorType: CAMERA
      carla_settings:
        PostProcessing: Depth
        ImageSizeX: 800
        ImageSizeY: 600
        FOV: 90
        PositionX: 1.80
        PositionY: 0
        PositionZ: 1.30
        RotationPitch: 0
        RotationRoll: 0
        RotationYaw: 0

    Lidar32:
      SensorType: LIDAR_RAY_CAST
      carla_settings:
        Channels: 32
        Range: 50
        PointsPerSecond: 100000
        RotationFrequency: 10
        UpperFovLimit: 1.6
        LowerFovLimit: -1.6
        PositionX: 0.0
        PositionY: 0
        PositionZ: 1.50
        RotationPitch: 0
        RotationYaw: 0
        RotationRoll: 0
